/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitarRouteImport } from './routes/solicitar'
import { Route as SolicitantesRouteImport } from './routes/solicitantes'
import { Route as SaidasRouteImport } from './routes/saidas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as DevolucoesRouteImport } from './routes/devolucoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque.index'
import { Route as ComprasIndexRouteImport } from './routes/compras.index'
import { Route as ComercialIndexRouteImport } from './routes/comercial.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FinanceiroDashboardRouteImport } from './routes/financeiro.dashboard'
import { Route as EstoqueAReceberRouteImport } from './routes/estoque.a-receber'
import { Route as EstoqueItemIdRouteImport } from './routes/estoque.$itemId'
import { Route as ComprasDashboardRouteImport } from './routes/compras.dashboard'
import { Route as ComercialValidacoesRouteImport } from './routes/comercial.validacoes'
import { Route as ComercialPropostasRouteImport } from './routes/comercial.propostas'
import { Route as ComercialClientesRouteImport } from './routes/comercial.clientes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminDadosRouteImport } from './routes/admin.dados'
import { Route as ApiPublicSolicitarRouteImport } from './routes/api/public/solicitar'

const SolicitarRoute = SolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitantesRoute = SolicitantesRouteImport.update({
  id: '/solicitantes',
  path: '/solicitantes',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidasRoute = SaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolucoesRoute = DevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasIndexRoute = ComprasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComprasRoute,
} as any)
const ComercialIndexRoute = ComercialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComercialRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FinanceiroDashboardRoute = FinanceiroDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FinanceiroRoute,
} as any)
const EstoqueAReceberRoute = EstoqueAReceberRouteImport.update({
  id: '/estoque/a-receber',
  path: '/estoque/a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueItemIdRoute = EstoqueItemIdRouteImport.update({
  id: '/estoque/$itemId',
  path: '/estoque/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasDashboardRoute = ComprasDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ComprasRoute,
} as any)
const ComercialValidacoesRoute = ComercialValidacoesRouteImport.update({
  id: '/validacoes',
  path: '/validacoes',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialPropostasRoute = ComercialPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialClientesRoute = ComercialClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => ComercialRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDadosRoute = AdminDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSolicitarRoute = ApiPublicSolicitarRouteImport.update({
  id: '/api/public/solicitar',
  path: '/api/public/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/compras': typeof ComprasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/devolucoes': typeof DevolucoesRoute
  '/entradas': typeof EntradasRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/saidas': typeof SaidasRoute
  '/solicitantes': typeof SolicitantesRoute
  '/solicitar': typeof SolicitarRoute
  '/admin/dados': typeof AdminDadosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/comercial/clientes': typeof ComercialClientesRoute
  '/comercial/propostas': typeof ComercialPropostasRoute
  '/comercial/validacoes': typeof ComercialValidacoesRoute
  '/compras/dashboard': typeof ComprasDashboardRoute
  '/estoque/$itemId': typeof EstoqueItemIdRoute
  '/estoque/a-receber': typeof EstoqueAReceberRoute
  '/financeiro/dashboard': typeof FinanceiroDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/api/public/solicitar': typeof ApiPublicSolicitarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/devolucoes': typeof DevolucoesRoute
  '/entradas': typeof EntradasRoute
  '/fornecedores': typeof FornecedoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/saidas': typeof SaidasRoute
  '/solicitantes': typeof SolicitantesRoute
  '/solicitar': typeof SolicitarRoute
  '/admin/dados': typeof AdminDadosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/comercial/clientes': typeof ComercialClientesRoute
  '/comercial/propostas': typeof ComercialPropostasRoute
  '/comercial/validacoes': typeof ComercialValidacoesRoute
  '/compras/dashboard': typeof ComprasDashboardRoute
  '/estoque/$itemId': typeof EstoqueItemIdRoute
  '/estoque/a-receber': typeof EstoqueAReceberRoute
  '/financeiro/dashboard': typeof FinanceiroDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/comercial': typeof ComercialIndexRoute
  '/compras': typeof ComprasIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/api/public/solicitar': typeof ApiPublicSolicitarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/comercial': typeof ComercialRouteWithChildren
  '/compras': typeof ComprasRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/devolucoes': typeof DevolucoesRoute
  '/entradas': typeof EntradasRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/fornecedores': typeof FornecedoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/saidas': typeof SaidasRoute
  '/solicitantes': typeof SolicitantesRoute
  '/solicitar': typeof SolicitarRoute
  '/admin/dados': typeof AdminDadosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/comercial/clientes': typeof ComercialClientesRoute
  '/comercial/propostas': typeof ComercialPropostasRoute
  '/comercial/validacoes': typeof ComercialValidacoesRoute
  '/compras/dashboard': typeof ComprasDashboardRoute
  '/estoque/$itemId': typeof EstoqueItemIdRoute
  '/estoque/a-receber': typeof EstoqueAReceberRoute
  '/financeiro/dashboard': typeof FinanceiroDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/api/public/solicitar': typeof ApiPublicSolicitarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/comercial'
    | '/compras'
    | '/dashboard'
    | '/devolucoes'
    | '/entradas'
    | '/financeiro'
    | '/fornecedores'
    | '/relatorios'
    | '/saidas'
    | '/solicitantes'
    | '/solicitar'
    | '/admin/dados'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/comercial/clientes'
    | '/comercial/propostas'
    | '/comercial/validacoes'
    | '/compras/dashboard'
    | '/estoque/$itemId'
    | '/estoque/a-receber'
    | '/financeiro/dashboard'
    | '/admin/'
    | '/comercial/'
    | '/compras/'
    | '/estoque/'
    | '/financeiro/'
    | '/api/public/solicitar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/devolucoes'
    | '/entradas'
    | '/fornecedores'
    | '/relatorios'
    | '/saidas'
    | '/solicitantes'
    | '/solicitar'
    | '/admin/dados'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/comercial/clientes'
    | '/comercial/propostas'
    | '/comercial/validacoes'
    | '/compras/dashboard'
    | '/estoque/$itemId'
    | '/estoque/a-receber'
    | '/financeiro/dashboard'
    | '/admin'
    | '/comercial'
    | '/compras'
    | '/estoque'
    | '/financeiro'
    | '/api/public/solicitar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/comercial'
    | '/compras'
    | '/dashboard'
    | '/devolucoes'
    | '/entradas'
    | '/financeiro'
    | '/fornecedores'
    | '/relatorios'
    | '/saidas'
    | '/solicitantes'
    | '/solicitar'
    | '/admin/dados'
    | '/admin/modulos'
    | '/admin/usuarios'
    | '/comercial/clientes'
    | '/comercial/propostas'
    | '/comercial/validacoes'
    | '/compras/dashboard'
    | '/estoque/$itemId'
    | '/estoque/a-receber'
    | '/financeiro/dashboard'
    | '/admin/'
    | '/comercial/'
    | '/compras/'
    | '/estoque/'
    | '/financeiro/'
    | '/api/public/solicitar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComercialRoute: typeof ComercialRouteWithChildren
  ComprasRoute: typeof ComprasRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DevolucoesRoute: typeof DevolucoesRoute
  EntradasRoute: typeof EntradasRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  FornecedoresRoute: typeof FornecedoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SaidasRoute: typeof SaidasRoute
  SolicitantesRoute: typeof SolicitantesRoute
  SolicitarRoute: typeof SolicitarRoute
  EstoqueItemIdRoute: typeof EstoqueItemIdRoute
  EstoqueAReceberRoute: typeof EstoqueAReceberRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
  ApiPublicSolicitarRoute: typeof ApiPublicSolicitarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitar': {
      id: '/solicitar'
      path: '/solicitar'
      fullPath: '/solicitar'
      preLoaderRoute: typeof SolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitantes': {
      id: '/solicitantes'
      path: '/solicitantes'
      fullPath: '/solicitantes'
      preLoaderRoute: typeof SolicitantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saidas': {
      id: '/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof SaidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolucoes': {
      id: '/devolucoes'
      path: '/devolucoes'
      fullPath: '/devolucoes'
      preLoaderRoute: typeof DevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/': {
      id: '/compras/'
      path: '/'
      fullPath: '/compras/'
      preLoaderRoute: typeof ComprasIndexRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/comercial/': {
      id: '/comercial/'
      path: '/'
      fullPath: '/comercial/'
      preLoaderRoute: typeof ComercialIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/financeiro/dashboard': {
      id: '/financeiro/dashboard'
      path: '/dashboard'
      fullPath: '/financeiro/dashboard'
      preLoaderRoute: typeof FinanceiroDashboardRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/estoque/a-receber': {
      id: '/estoque/a-receber'
      path: '/estoque/a-receber'
      fullPath: '/estoque/a-receber'
      preLoaderRoute: typeof EstoqueAReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/$itemId': {
      id: '/estoque/$itemId'
      path: '/estoque/$itemId'
      fullPath: '/estoque/$itemId'
      preLoaderRoute: typeof EstoqueItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/dashboard': {
      id: '/compras/dashboard'
      path: '/dashboard'
      fullPath: '/compras/dashboard'
      preLoaderRoute: typeof ComprasDashboardRouteImport
      parentRoute: typeof ComprasRoute
    }
    '/comercial/validacoes': {
      id: '/comercial/validacoes'
      path: '/validacoes'
      fullPath: '/comercial/validacoes'
      preLoaderRoute: typeof ComercialValidacoesRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/propostas': {
      id: '/comercial/propostas'
      path: '/propostas'
      fullPath: '/comercial/propostas'
      preLoaderRoute: typeof ComercialPropostasRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/clientes': {
      id: '/comercial/clientes'
      path: '/clientes'
      fullPath: '/comercial/clientes'
      preLoaderRoute: typeof ComercialClientesRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dados': {
      id: '/admin/dados'
      path: '/dados'
      fullPath: '/admin/dados'
      preLoaderRoute: typeof AdminDadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/solicitar': {
      id: '/api/public/solicitar'
      path: '/api/public/solicitar'
      fullPath: '/api/public/solicitar'
      preLoaderRoute: typeof ApiPublicSolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDadosRoute: typeof AdminDadosRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDadosRoute: AdminDadosRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ComercialRouteChildren {
  ComercialClientesRoute: typeof ComercialClientesRoute
  ComercialPropostasRoute: typeof ComercialPropostasRoute
  ComercialValidacoesRoute: typeof ComercialValidacoesRoute
  ComercialIndexRoute: typeof ComercialIndexRoute
}

const ComercialRouteChildren: ComercialRouteChildren = {
  ComercialClientesRoute: ComercialClientesRoute,
  ComercialPropostasRoute: ComercialPropostasRoute,
  ComercialValidacoesRoute: ComercialValidacoesRoute,
  ComercialIndexRoute: ComercialIndexRoute,
}

const ComercialRouteWithChildren = ComercialRoute._addFileChildren(
  ComercialRouteChildren,
)

interface ComprasRouteChildren {
  ComprasDashboardRoute: typeof ComprasDashboardRoute
  ComprasIndexRoute: typeof ComprasIndexRoute
}

const ComprasRouteChildren: ComprasRouteChildren = {
  ComprasDashboardRoute: ComprasDashboardRoute,
  ComprasIndexRoute: ComprasIndexRoute,
}

const ComprasRouteWithChildren =
  ComprasRoute._addFileChildren(ComprasRouteChildren)

interface FinanceiroRouteChildren {
  FinanceiroDashboardRoute: typeof FinanceiroDashboardRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroDashboardRoute: FinanceiroDashboardRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ComercialRoute: ComercialRouteWithChildren,
  ComprasRoute: ComprasRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DevolucoesRoute: DevolucoesRoute,
  EntradasRoute: EntradasRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  FornecedoresRoute: FornecedoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  SaidasRoute: SaidasRoute,
  SolicitantesRoute: SolicitantesRoute,
  SolicitarRoute: SolicitarRoute,
  EstoqueItemIdRoute: EstoqueItemIdRoute,
  EstoqueAReceberRoute: EstoqueAReceberRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
  ApiPublicSolicitarRoute: ApiPublicSolicitarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
