ALTER TABLE public.demanda_itens
  ADD COLUMN IF NOT EXISTS desconto numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS frete numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ipi numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outros_custos numeric NOT NULL DEFAULT 0;